USE LOGITICA;
GO

INSERT INTO TBOD_CLIENTE (
	CD_CLIENTE,
	NM_EMPRESA,
	NM_CONTATO,
	DS_CARGO,
	DS_CIDADE,
	DS_PAIS
	)
	VALUES(
	(SELECT MAX(*)+1 FROM TBOD_CLIENTE),
	'United Artist Records',
	'David Coverdale',
	'Gerente de marketing',
	'Reino Unido',
	'Londres'
	);

SELECT * FROM TBOD_CLIENTE WHERE CD_CLIENTE =(SELECT MAX(CD_CLIENTE) FROM TBOD_CLIENTE);

DELETE FROM TBOD_CLIENTE
	WHERE CD_CLIENTE =(SELECT MAX(CD_CLIENTE) FROM TBOD_CLIENTE);
