USE LOGITICA;
GO
--OPERADOR AND
SELECT * FROM TBOD_DETALHES_PEDIDO
	WHERE QT_TOTAL >= 50 AND QT_TOTAL <= 100;


--OPERADOR BETWEEN
SELECT * FROM TBOD_DETALHES_PEDIDO
	WHERE QT_TOTAL BETWEEN 50 AND 100;

--OPERADOR IN
