USE LOGITICA;
GO
CREATE TABLE TBOD_CLIENTE(
	CD_CLIENTE CHAR(10) NOT NULL PRIMARY KEY,
	NM_EMPRESA VARCHAR(70) NOT NULL ,
	NM_CONTATO VARCHAR(70) NOT NULL ,
	DS_CARGO VARCHAR(40) NOT NULL,
	DS_ENDERECO VARCHAR(50),
	DS_CIDADE VARCHAR(25),
	DS_REGIAO VARCHAR(25),
	NR_CEP VARCHAR(15),
	DS_PAIS VARCHAR(25),
	NR_TELEFONE CHAR(20),
	NR_FAX CHAR(20)
);