--TBOD_PEDIDO
USE LOGITICA;
GO
CREATE TABLE TBOD_PEDIDO
(
	NR_PEDIDO INT NOT NULL PRIMARY KEY,
	CD_CLEINTE CHAR(10) FOREIGN KEY REFERENCES dbo.TBOD_CLIENTE(CD_CLIENTE),
	CD_FUNCIONARIO INT  FOREIGN KEY REFERENCES dbo.TBOD_FUNCIONARIO(CD_FUNCIONARIO),
	DT_PEDIDO DATE,
	DT_ENTREGA DATE,
	DT_ENVIO DATE,
	CD_TRANSPORTADORA INT FOREIGN KEY REFERENCES dbo.TBOD_TRANSPORTADORA(CD_TRANSPORTADORA), 
	VL_FRETE MONEY,
	NM_DESTINATARIO VARCHAR(50),
	DS_ENDERECO_DESTINATARIO VARCHAR(50),
	DS_CEP_DESTINATARIO CHAR(15),
	DS_PAIS_DESTINATARIO VARCHAR(25),
	DS_CIDADE_DESTINATARIO VARCHAR(25),
	DS_REGIAO_DESTINATARIO VARCHAR(25)
);
