--TBOD_FUNCIONARIO
USE LOGITICA;
GO
CREATE TABLE TBOD_FUNCIONARIO
(
	CD_FUNCIONARIO INT NOT NULL PRIMARY KEY,
	NM_NOME VARCHAR(30),
	NM_SOBRENOME VARCHAR(30) NOT NULL,
	DS_CARGO VARCHAR(40),
	DS_TRATAMENTO VARCHAR(10),
	DT_NASCIMENTO DATE,
	DT_CONTRATACAO DATE,
	DS_ENDERECO VARCHAR(50),
	DS_CIDADE VARCHAR(25),
	DS_REGIAO VARCHAR(25),
	DS_CEP CHAR(15),
	DS_PAIS VARCHAR(25),
	NR_TELEFONE_RESIDENCIAL CHAR(20),
	NR_RAMAL CHAR(5),
	DS_OBSERVACOES VARCHAR(200)
);