--TBOD_DETALHES_PEDIDO
USE LOGITICA;
GO
CREATE TABLE TBOD_DETALHES_PEDIDO
(
	NR_PEDIDO INT FOREIGN KEY REFERENCES dbo.TBOD_PEDIDO(NR_PEDIDO),
	CD_PRODUTO INT FOREIGN KEY REFERENCES dbo.TBOD_PRODUTO(CD_PRODUTO),
	VL_PRECO MONEY,
	QT_TOTAL INT,
	PC_DESCONTO FLOAT
);